version: 2
updates:
  - package-ecosystem: "npm" # Node.js 패키지 보안 검사
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions" # Actions 파이프라인 보안 검사
    directory: "/"
    schedule:
      interval: "weekly"