name: 과제 3 Secrets 활용 실습

on:
  push:
    branches: [ "main" ]

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: API 키 환경 변수로 불러오기 및 마스킹 확인
        # env 키워드를 사용하여 Secret 값을 환경 변수로 매핑 (슬라이드 3번 조건)
        env:
          API_KEY: ${{ secrets.API_KEY }} # 슬라이드 2번 조건 문법
        run: |
          echo "저장된 API_KEY 값을 출력합니다:"
          echo "$API_KEY"
          echo "로그에 실제 값이 보이지 않고 별표(***)로 마스킹 처리되면 완벽한 성공입니다!"